# Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/FiXUnique/QuickCommands
build-by-default: true
branches:
  - main
projects:
  - path: .
    main: QuickCommands\Main
    output: QuickCommands.phar
