---
# Poggit-CI Manifest for QuickCommands
build-by-default: true
branches:
  - main
projects:
  - name: QuickCommands
    path: .
    type: plugin
    entry: src/FiX/QuickCommands/Main.php
    api:
      - 5.0.0
    version: 1.0.0
    description: "Fast utility commands for PocketMine"
...
